name: Auto Merge Dependabot PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
    - name: Merge pull request
      run: gh pr merge --auto --merge ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.DEPBOT_TOKEN }}
        GH_REPO: ${{ github.repository }}
